### ISSUE TITLE
Icon color

### ISSUE THREAD

**Issue by nagyrobi** [amaximus/fkf-garbage-collection-card#1]
Please implement usage of inverted colors for icons when theme/background is dark:
![kép](https://user-images.githubusercontent.com/1550668/80954974-b076b280-8dfe-11ea-8b34-12f829f364ee.png)
I temporarily fix it by changing to `--iron-icon-fill-color: white;`

Köszönjük!

**Comment by amaximus** [comment]
Added support for dark background in version 0.4.0.
Please update and get back to me with information.

**Comment by nagyrobi** [comment]
Still not good: I am using material dark theme below as default theme both day and night.
The icon doesn't recognize it. I think it should use `primary-text-color` from the theme, rather than specifying the color directly.
```
material_dark_red_robi:
  dark-primary-color: "#c66900"
  disabled-text-color: "#545454"
  divider-color: "#262626"
  light-primary-color: "#e06c6c"
  paper-card-background-color: "#262626"
  paper-grey-200: "#191919"
  paper-item-icon-color: "#d3d3d3"
  paper-listbox-background-color: "var(--paper-card-background-color)"
  primary-background-color: "#272822"
  primary-color: "#d32f2f"
  primary-text-color: "#cfcfcf"
  secondary-background-color: "#000000"
  sidebar-text_-_background: "#262626"
  sidebar-icon-color: "var(--paper-item-icon-color)"
  paper-card-header-color: "var(--paper-item-icon-color)"
  paper-item-icon-active-color: "var(--primary-color)"
  paper-item-icon_-_color: "var(--paper-item-icon-color)"
  paper-listbox-color: "var(--primary-text-color)"
  paper-grey-50: "var(--primary-text-color)"
  paper-slider-active-color: "var(--primary-color)"
  paper-slider-knob-color: "var(--primary-color)"
  paper-slider-knob-start-color: "var(--primary-color)"
  paper-slider-pin-color: "var(--primary-color)"
  paper-slider-secondary-color: "var(--light-primary-color)"
  paper-toggle-button-checked-ink-color: "var(--dark-primary-color)"
  paper-toggle-button-checked-button-color: "var(--primary-color)"
  paper-toggle-button-checked-bar-color: "var(--light-primary-color)"
  paper-toggle-button-unchecked-bar-color: "var(--primary-text-color)"
  secondary-text-color: "var(--primary-color)"
  table-row-background-color: "var(--paper-card-background-color)"
  table-row-alternative-background-color: "var(--sidebar-text_-_background)"
  card-background-color: var(--paper-card-background-color)
```
